/**
 * The drawing tools are one implementation, and this is what says so.
 *
 * `services/port-draw-tools.py` copies the Earth viewer's press-drag
 * apparatus into the five rocky planet viewers, because those files are
 * self-contained copies with no module they could share. A copy that is
 * never checked is a copy that drifts — the polygon-area formula was wrong
 * in nine viewers for exactly this reason, and it took a user noticing a
 * 200 km box measuring 106 km to find it.
 *
 * So this asserts the generated blocks are byte-for-byte what the porter
 * would write today. Edit earth-viewer.js, re-run the porter, and this
 * passes; edit a planet's copy by hand, and it fails here rather than in
 * somebody's session six months from now.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");

let failures = 0;
function check(name, got, want) {
  const ok = JSON.stringify(got) === JSON.stringify(want);
  if (!ok) {
    failures += 1;
    console.log(`FAIL ${name}\n  got  ${JSON.stringify(got)}\n  want ${JSON.stringify(want)}`);
  } else {
    console.log(`PASS ${name}`);
  }
}

// Kept in step with BODIES in services/port-draw-tools.py by the last two
// checks below, which read that file rather than trusting this copy.
const BODIES = [
  ["mars", "mars-viewer.js", "marsGroup", "MARS_MEAN_RADIUS_KM"],
  ["moon", "moon-viewer.js", "marsGroup", "MOON_MEAN_RADIUS_KM"],
  ["mercury", "mercury-viewer.js", "mercuryGroup", "MERCURY_MEAN_RADIUS_KM"],
  ["venus", "venus-viewer.js", "venusGroup", "VENUS_MEAN_RADIUS_KM"],
  ["pluto", "pluto-viewer.js", "plutoGroup", "PLUTO_MEAN_RADIUS_KM"],
];

const OPEN_MARK = "// >>> GEOID-DRAW-TOOLS — generated by services/port-draw-tools.py";
const CLOSE_MARK = "// <<< GEOID-DRAW-TOOLS";
const BLOCK_START = "      /* ── Study-area rectangle editing";
const BLOCK_END = '      window.addEventListener("pointerup", drawPointerUp, true);\n';

const earth = readFileSync(join(ROOT, "GeoID_GIS", "viewer", "earth-viewer.js"), "utf-8");
const blockStart = earth.indexOf(BLOCK_START);
const blockEnd = earth.indexOf(BLOCK_END);
check("the Earth viewer still holds the block the port is taken from",
  blockStart > 0 && blockEnd > blockStart, true);
const block = earth.slice(blockStart, blockEnd + BLOCK_END.length);

/** The porter's own transformation, restated. */
function render(group, radiusConst) {
  let out = block.replace(/\blonDelta\b/g, "studyLonDelta");
  out = out.split("111.32").join("DRAW_KM_PER_DEG");
  if (group !== "marsGroup") out = out.replace(/\bmarsGroup\b/g, group);
  const header = `      ${OPEN_MARK}\n`
    + "      // Edit earth-viewer.js and re-run that script; a hand edit here\n"
    + "      // is overwritten, and worse, silently diverges until it is.\n"
    + `      const DRAW_KM_PER_DEG = (2 * Math.PI * ${radiusConst}) / 360;\n`;
  return header + out + `      ${CLOSE_MARK}\n`;
}

for (const [folder, viewer, group, radiusConst] of BODIES) {
  const path = join(ROOT, "planet_explorer", folder, "viewer", viewer);
  const text = readFileSync(path, "utf-8");
  const from = text.indexOf(`      ${OPEN_MARK}`);
  const to = text.indexOf(`      ${CLOSE_MARK}\n`);
  check(`${folder} carries a generated drawing block`, from > 0 && to > from, true);
  if (from < 0 || to < from) continue;
  const found = text.slice(from, to + `      ${CLOSE_MARK}\n`.length);
  check(`${folder}'s drawing block matches the Earth viewer's`, found === render(group, radiusConst), true);
  // The three things that are genuinely per-body.
  check(`${folder} measures kilometres with its OWN radius`,
    found.includes(`(2 * Math.PI * ${radiusConst}) / 360`), true);
  check(`${folder} has no Earth kilometres left in it`, found.includes("111.32"), false);
  /* Handles and labels must project through the frame the GEOMETRY is in.
     `measureGroup` carries the globe's spin and the drawn outline is its
     child; the body group above it does not. Projecting through the parent
     drew the handles in the baseline frame and the shape in the spun one, so
     the two parted by however far the planet had turned — measured on Mars
     as ~10° of longitude, 592 km, at every corner with latitude exact. The
     variable is named `measureGroup` in every viewer and parented to that
     body's own group, so this needs no per-body rewrite; what it does need
     is never to go back to the parent. */
  check(`${folder} projects through the spin-carrying measure frame`,
    found.includes("measureFrameGroup(context).localToWorld"), true);
  check(`${folder} does NOT project through the body group above it`,
    found.includes(`${group}.localToWorld`), false);
  // The seams the HUD's Done and Cancel call, and the announcement
  // gis/pipeline-sync.js listens for.
  check(`${folder} exposes clearStudyArea`, text.includes("clearStudyArea()"), true);
  check(`${folder} announces an edited study area`,
    text.includes('new Event("geoid-study-area-edited")'), true);
}

// The gas giants must NOT have it: no surface to draw on, and a HUD there
// would be four inert buttons. This is the check that keeps a future
// "port it everywhere" from quietly shipping them.
for (const folder of ["jupiter", "saturn", "uranus", "neptune"]) {
  const dir = join(ROOT, "planet_explorer", folder, "viewer");
  const names = ["saturn-viewer.js", `${folder}-viewer.js`];
  let carries = false;
  for (const name of names) {
    try {
      if (readFileSync(join(dir, name), "utf-8").includes(OPEN_MARK)) carries = true;
    } catch { /* that lineage has no such file */ }
  }
  check(`${folder} is left alone — a gas giant has no surface to draw on`, carries, false);
}

// The porter's body list is the authority; this file's copy must match it,
// or a world added there is silently untested here.
const porter = readFileSync(join(ROOT, "GeoID_GIS", "services", "port-draw-tools.py"), "utf-8");
for (const [folder, viewer, group, radiusConst] of BODIES) {
  check(`the porter still files ${folder} the same way`,
    porter.includes(`("${folder}",`) && porter.includes(`"${viewer}"`)
    && porter.includes(`"${group}"`) && porter.includes(`"${radiusConst}"`), true);
}

if (failures) {
  console.log(`\n${failures} check(s) failed`);
  process.exit(1);
}
console.log("\nall checks passed");
