#!/usr/bin/env python3
"""Carry the Earth viewer's drawing gestures to the rocky planet viewers.

The press-drag box, the eight visible handles, the live size chip, the
hover cursors and the Escape cancel were written once, in earth-viewer.js.
Every planet viewer is a self-contained COPY of the viewer — there is no
shared module they could import, and `stamp.py` deliberately does not sweep
`planet_explorer/**/*.js` (those files carry epoch-second stamps from
another tooling convention, and an 8-digit rewrite mangles them). So the
choice is five hand-maintained copies or one generator, and this file is
the generator: the copies are marked, so re-running replaces them.

**Edit earth-viewer.js and re-run this. Never edit a generated block.**
That is the lesson the polygon-area formula cost — the same arithmetic
written out in ten places, corrected in one.

Three things are per-body and are rewritten here:

  * the scene group that carries the tilt and spin (`marsGroup` on Earth,
    Mars and the Moon; each of the other worlds has its own),
  * the kilometres in a degree — 111.32 is Earth's and nobody else's, so
    it comes off each viewer's own mean-radius constant,
  * `lonDelta`, which already means something else in these files.

Run:  python3 GeoID_GIS/services/port-draw-tools.py [--check]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EARTH = ROOT / "GeoID_GIS" / "viewer" / "earth-viewer.js"

OPEN_MARK = "// >>> GEOID-DRAW-TOOLS — generated by services/port-draw-tools.py"
CLOSE_MARK = "// <<< GEOID-DRAW-TOOLS"

# The gas giants are absent on purpose: they have no activateStudyArea and
# no surface to draw on. That is a fact about the bodies, not a gap.
BODIES = [
    # folder,   viewer file,          scene group,     mean-radius constant
    ("mars",    "mars-viewer.js",     "marsGroup",     "MARS_MEAN_RADIUS_KM"),
    ("moon",    "moon-viewer.js",     "marsGroup",     "MOON_MEAN_RADIUS_KM"),
    ("mercury", "mercury-viewer.js",  "mercuryGroup",  "MERCURY_MEAN_RADIUS_KM"),
    ("venus",   "venus-viewer.js",    "venusGroup",    "VENUS_MEAN_RADIUS_KM"),
    ("pluto",   "pluto-viewer.js",    "plutoGroup",    "PLUTO_MEAN_RADIUS_KM"),
]

# Where the block goes: straight after the measurement raycast it is built
# on, exactly where it sits in the Earth viewer.
ANCHOR = (
    "        return { ...hit, localPoint, lat: latLon.lat, "
    "lon: latLon.lon, context };\n      }\n"
)

BLOCK_START = "      /* ── Study-area rectangle editing"
BLOCK_END = '      window.addEventListener("pointerup", drawPointerUp, true);\n'

SEAM_OLD = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          return true;
        },
"""

SEAM_NEW = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          // Announced like an edit: gis/pipeline-sync.js listens here, so
          // every creator — a preset, the Draw HUD, a restored area — keeps
          // the open project's study area current.
          document.dispatchEvent(new Event("geoid-study-area-edited"));
          return true;
        },
        // The drawn overlay, taken down — used once a shape has been
        // CAPTURED as a real layer, so the floating outline does not double
        // the relief-hugging one beneath it.
        clearStudyArea() {
          resetActiveMeasurement();
        },
"""


def earth_block() -> str:
    """The drawing apparatus, lifted verbatim from the Earth viewer."""
    src = EARTH.read_text(encoding="utf-8")
    start = src.index(BLOCK_START)
    end = src.index(BLOCK_END) + len(BLOCK_END)
    return src[start:end]


def render(block: str, group: str, radius_const: str) -> str:
    """The same code, speaking this body's own frame and units."""
    out = block
    # `lonDelta` is already a local in these files; a hoisted function
    # declaration beside a const of that name is a SyntaxError, and one
    # that only bites the world whose file happens to have both.
    out = re.sub(r"\blonDelta\b", "studyLonDelta", out)
    # A kilometre is not a degree anywhere except Earth.
    out = out.replace("111.32", "DRAW_KM_PER_DEG")
    if group != "marsGroup":
        out = re.sub(r"\bmarsGroup\b", group, out)
    header = (
        f"      {OPEN_MARK}\n"
        "      // Edit earth-viewer.js and re-run that script; a hand edit here\n"
        "      // is overwritten, and worse, silently diverges until it is.\n"
        f"      const DRAW_KM_PER_DEG = (2 * Math.PI * {radius_const}) / 360;\n"
    )
    return header + out + f"      {CLOSE_MARK}\n"


def apply(text: str, rendered: str) -> str:
    """Insert the block, or replace the one already there."""
    if OPEN_MARK in text:
        pattern = re.compile(
            r"[ \t]*" + re.escape(OPEN_MARK) + r".*?" + re.escape(CLOSE_MARK) + r"\n",
            re.DOTALL,
        )
        return pattern.sub(rendered, text, count=1)
    if text.count(ANCHOR) != 1:
        raise SystemExit(f"anchor not found exactly once ({text.count(ANCHOR)})")
    return text.replace(ANCHOR, ANCHOR + "\n" + rendered, 1)


def main() -> int:
    check = "--check" in sys.argv
    block = earth_block()
    stale = []
    for folder, viewer, group, radius_const in BODIES:
        path = ROOT / "planet_explorer" / folder / "viewer" / viewer
        text = path.read_text(encoding="utf-8")
        if radius_const not in text:
            raise SystemExit(f"{folder}: {radius_const} not found")
        updated = apply(text, render(block, group, radius_const))
        # The seam the HUD's Done and Cancel need, and the announcement the
        # pipeline sync listens for.
        if SEAM_OLD in updated:
            updated = updated.replace(SEAM_OLD, SEAM_NEW, 1)
        elif "clearStudyArea()" not in updated:
            raise SystemExit(f"{folder}: setStudyAreaPolygon seam not recognised")
        if updated == text:
            print(f"  {folder:8s} unchanged")
            continue
        stale.append(folder)
        if not check:
            path.write_text(updated, encoding="utf-8")
        print(f"  {folder:8s} {'STALE' if check else 'ported'}")
    if check and stale:
        print(f"drawing tools out of date on: {', '.join(stale)}")
        return 1
    print("uniform" if not stale else f"ported {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
