#!/usr/bin/env python3
"""
Publish each rocky viewer's own terrain primitives on the GIS seam.

The GIS tools ARE one shared module set — 51 modules under `viewer/gis/`, the
same 47-tool registry and the same draw bar on every world. What was NOT shared
is the SEAM those modules call into: `window.GeoIDViewer`. Measured live on
Mars, three names the shared modules use were simply absent:

    surfacePoint          vector-render, the drapes, anything that hugs terrain
    getEffectiveRelief    vector-render, geotiff-adapter
    elevationNormalized   vector-render

Every one of those is already COMPUTED inside each planet viewer — as
`measureSurfaceRadius`, `getEffectiveTerrainRelief` and
`sampleElevationNormalized`. They were just never published, so a shared module
loaded on a planet asked for them and got `undefined`.

So this does not re-derive the terrain rule in a shared module, which is the
"second implementation drifts" trap this tree has paid for repeatedly (the
polygon-area formula in ten files, the imitated label engine, the fan apex).
It exposes what each viewer already has, in that viewer's own frame.

`surfacePoint` passes an explicit `{ kind: "planet" }` context rather than
letting `measureSurfaceRadius` default to `getActiveMeasureContext()`: the
default would answer in a MOON's frame whenever a moon happens to be the active
measure target, and a caller asking for a point on the planet must get one.

The four gas giants are deliberately untouched: they have no elevation map and
no `getEffectiveTerrainRelief`, so there is nothing to publish and nothing that
hugs their terrain.

Run:  python3 GeoID_GIS/services/port-viewer-seam.py [--check]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORLDS = ["mars", "mercury", "moon", "venus", "pluto"]

# The card seam goes to ALL NINE: a gas giant has no terrain to hug, but it has
# a scene card, and leaving GIS has to dismiss it there too.
CARD_WORLDS = WORLDS + ["jupiter", "saturn", "uranus", "neptune"]

# The seam literal already lists this; the new entries go directly after it.
ANCHOR = "        sphericalPolygonAreaKm2,\n"

BLOCK = """        // ── Terrain seam, published for the shared GIS modules ──────────
        // These three are what vector-render and the raster adapters ask a
        // viewer for so their geometry can hug the ground. Each is this
        // viewer's OWN computation, exposed rather than re-derived: a second
        // copy of the radius rule is exactly how the polygon-area formula came
        // to be wrong in ten files.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        surfacePoint: (lat, lon, lift = 0) => latLonToVector3(
          lat, lon, measureSurfaceRadius(lat, lon, lift, { kind: "planet" })),
        getEffectiveRelief: () => getEffectiveTerrainRelief(),
        elevationNormalized: (lat, lon) => (elevationSampler
          ? sampleElevationNormalized(elevationSampler, lat, lon) : 0),
"""

MARK = "Terrain seam, published for the shared GIS modules"

CARD_BLOCK = """        // ── Floating cards, so a mode change can dismiss them ───────────
        // A scene card is a fixed element on `body`, so nothing that hides the
        // sidebar touches it: leaving GIS left one standing over the Model
        // studio and the Research Hub. It closes through each card's OWN
        // closer, because `closeScenePopup` also clears the temporary
        // selection label and the selection halo — hiding the element alone
        // strands a pulsing marker on a globe nobody can see.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        closeCards: () => {
          if (typeof closeScenePopup === "function") closeScenePopup();
          if (typeof closeGeoPopup === "function") closeGeoPopup();
          if (typeof hideMeasurementResultCard === "function") hideMeasurementResultCard();
        },
"""

CARD_MARK = "Floating cards, so a mode change can dismiss them"


def target(world: str) -> Path:
    return ROOT / "planet_explorer" / world / "viewer" / f"{world}-viewer.js"


def apply_cards(check: bool) -> int:
    """The card seam, on every world including the four gas giants."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        anchor = f'        bodyId: "{world}",\n'
        if anchor not in src:
            print(f"  {world:<9} ANCHOR MISSING (cards)")
            stale += 1
            continue
        if CARD_MARK in src:
            src = re.sub(
                r"[ ]*// ── Floating cards.*?\n[ ]*\},\n", "", src, flags=re.S)
        want = src.replace(anchor, anchor + CARD_BLOCK, 1)
        if check:
            if path.read_text(encoding="utf-8") != want:
                print(f"  {world:<9} STALE (cards)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (cards)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} card seam written")
    return stale


def apply(check: bool) -> int:
    stale = 0
    for world in WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        if ANCHOR not in src:
            print(f"  {world:<9} ANCHOR MISSING — seam literal changed shape")
            stale += 1
            continue
        # Idempotent: strip a previous block before writing the current one.
        if MARK in src:
            src = re.sub(
                r"[ ]*// ── Terrain seam.*?elevationNormalized: \(lat, lon\) => \(elevationSampler\n"
                r".*?: 0\),\n",
                "", src, flags=re.S)
        want = src.replace(ANCHOR, ANCHOR + BLOCK, 1)
        if check:
            current = path.read_text(encoding="utf-8")
            if current != want:
                print(f"  {world:<9} STALE")
                stale += 1
            else:
                print(f"  {world:<9} up to date")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} seam published")
    return stale


CUT_BLOCK = """        // ── What the scene is cut by, so a layer can cut itself ─────────
        // Core View removes half the planet with one world-space clipping
        // plane, and that plane was applied to a hand-written list of this
        // viewer's OWN materials. Everything the shared GIS modules draw was
        // outside that list, so with the cutaway up a coastline, a marker
        // cloud or a dot layer went on being drawn across the removed half.
        //
        // A list cannot be the answer -- a layer's materials are built by the
        // importer, the tilers, the drapes and the repaints -- so the plane is
        // published and `gis/cutaway.js` stamps whatever is on the globe now.
        // Live rather than copied: the normal is re-aimed whenever the axial
        // tilt changes, and three.js reads clipping planes in WORLD space.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        getCutawayPlanes: () => (coreToggle && coreToggle.checked ? [cutawayClipPlane] : []),
"""

CUT_MARK = "What the scene is cut by, so a layer can cut itself"

# The last line of CARD_BLOCK. Anchoring here rather than on `bodyId` keeps the
# two blocks in a FIXED order however often the porter is re-run: `apply_cards`
# strips and re-inserts its own block at `bodyId`, which puts it back above
# this one, and this block is re-inserted after it. Anchored both on `bodyId`
# the order would flip on every run and `--check` would never settle.
CUT_ANCHOR = ('          if (typeof hideMeasurementResultCard === "function")'
              " hideMeasurementResultCard();\n        },\n")

# The one line every viewer's core toggle builds its plane list on.
TOGGLE_ANCHOR = "        const planes = enabled ? [cutawayClipPlane] : [];\n"

TOGGLE_BLOCK = """        // Announced, because the layers are not ours to enumerate: the
        // viewer stamps its own materials inline and everything the GIS page
        // put on the globe hears this instead. A plain Event on `document`,
        // which is this tree's own viewer-side convention.
        // Generated by services/port-viewer-seam.py — do not hand-edit.
        document.dispatchEvent(new Event("geoid-gis:cutaway-changed"));
"""

TOGGLE_MARK = "Announced, because the layers are not ours to enumerate"


def apply_cutaway(check: bool) -> int:
    """The cutaway seam and its announcement, on every world -- gas giants
    included, since all ten have a core toggle and all ten take layers."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        want = src
        if CUT_MARK in want:
            want = re.sub(r"[ ]*// ── What the scene is cut by.*?getCutawayPlanes:.*?\n",
                          "", want, flags=re.S)
        if TOGGLE_MARK in want:
            want = re.sub(r"[ ]*// Announced, because the layers are not ours.*?"
                          r'document\.dispatchEvent\(new Event\("geoid-gis:cutaway-changed"\)\);\n',
                          "", want, flags=re.S)
        if CUT_ANCHOR not in want or TOGGLE_ANCHOR not in want:
            missing = "card block" if CUT_ANCHOR not in want else "core toggle"
            print(f"  {world:<9} ANCHOR MISSING ({missing})")
            stale += 1
            continue
        want = want.replace(CUT_ANCHOR, CUT_ANCHOR + CUT_BLOCK, 1)
        want = want.replace(TOGGLE_ANCHOR, TOGGLE_BLOCK + TOGGLE_ANCHOR, 1)
        if check:
            if path.read_text(encoding="utf-8") != want:
                print(f"  {world:<9} STALE (cutaway)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (cutaway)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} cutaway seam written")
    return stale


# ── The spin a layer must follow ─────────────────────────────────────────────
#
# Every planet published `getSpinDeltaRadians` as its planet GROUP's rotation,
# and no planet turns its group: the globe mesh spins inside it. So the seam
# answered a constant 0 on all nine, and the shared modules that asked it
# (events.js, demo-layers.js) placed things for a planet that never turns.
#
# import-manager then stopped asking and read `globe.rotation.y - PI` instead,
# which is Earth's rule — Earth's globe carries a half-turn on top of its spin.
# Mars, Mercury, Venus and the Moon carry the same half-turn; Pluto does not
# (its texture offset is taken up elsewhere), so every GIS layer on Pluto was
# spun 180 degrees onto the FAR side. Measured: a drawn study area whose outline
# faced the camera at -0.995 — rendered every frame, culled every fragment.
#
# The frame a layer must share is the one the viewer draws its OWN study areas
# in, `measureGroup`, which each viewer turns with its globe by its own rule.
# Publishing that is the viewer's answer rather than a second derivation.
SPIN_RE = re.compile(
    r"getSpinDeltaRadians: \(\) => \(\w+Group \? \w+Group\.rotation\.y : 0\),\n")
SPIN_NEW = ("getSpinDeltaRadians: () => (measureGroup ? measureGroup.rotation.y : 0),"
            "  // generated by services/port-viewer-seam.py\n")


def apply_spin(check: bool) -> int:
    """The layer frame, on all nine worlds."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        if SPIN_NEW in src:
            want = src
        elif SPIN_RE.search(src):
            want = SPIN_RE.sub(SPIN_NEW, src, count=1)
        else:
            print(f"  {world:<9} ANCHOR MISSING (spin)")
            stale += 1
            continue
        if check:
            if src != want:
                print(f"  {world:<9} STALE (spin)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (spin)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} spin seam written")
    return stale



PICK_BLOCK = """        // ── Screen to ground, for the shared pickers ─────────────────────
        // feature-popup asks the viewer which lat/lon a pixel is, then tests
        // it against each layer's own coordinates. No planet published this,
        // so a click on an imported layer never opened its card on any planet.
        // The answer is read in the IMPORTED LAYERS' OWN FRAME, as the exact
        // inverse of how their vertices were placed (latLonToVector3's own
        // axes), so a west-positive world (Mercury) reads back the same
        // longitude it was drawn from. The sphere is walked onto the drawn
        // relief, since a raycast against the bare sphere lands beside
        // the terrain at an oblique view. Signed -180..180, as GeoJSON is.
        //
        // Generated by services/port-viewer-seam.py -- edit the generator.
        surfaceLatLonAt: (clientX, clientY) => {
          const frame = scene.getObjectByName("GeoID-ImportedGeoLayers");
          const rect = renderer.domElement.getBoundingClientRect();
          if (!frame || !rect.width || !rect.height) return null;
          const ray = new THREE.Raycaster();
          ray.setFromCamera(new THREE.Vector2(((clientX - rect.left) / rect.width) * 2 - 1,
            -((clientY - rect.top) / rect.height) * 2 + 1), camera);
          frame.updateWorldMatrix(true, false);
          const centre = new THREE.Vector3().setFromMatrixPosition(frame.matrixWorld);
          const scale = new THREE.Vector3().setFromMatrixScale(frame.matrixWorld).x || 1;
          // latLonToVector3 read backwards: its own directions for 0 deg, 90 deg
          // and the pole. vectorToLatLon is NOT always its inverse -- on
          // Mercury it answered 53.5 deg for Beethoven's 124.2 -- and this
          // is, whatever the world's longitude convention.
          const axes = {
            east0: latLonToVector3(0, 0, 1).normalize(),
            east90: latLonToVector3(0, 90, 1).normalize(),
            pole: latLonToVector3(90, 0, 1).normalize(),
          };
          let radius = 3.2;
          let latLon = null;
          for (let round = 0; round < 4; round += 1) {
            const world = new THREE.Vector3();
            if (!ray.ray.intersectSphere(new THREE.Sphere(centre, radius * scale), world)) break;
            const u = frame.worldToLocal(world).normalize();
            latLon = {
              lat: THREE.MathUtils.radToDeg(Math.asin(Math.max(-1, Math.min(1, u.dot(axes.pole))))),
              lon: ((THREE.MathUtils.radToDeg(Math.atan2(u.dot(axes.east90), u.dot(axes.east0))) % 360) + 360) % 360,
            };
            let next = radius;
            try { next = measureSurfaceRadius(latLon.lat, latLon.lon, 0, { kind: "planet" }); } catch (_e) { break; }
            if (!Number.isFinite(next) || Math.abs(next - radius) < 1e-7) break;
            radius = next;
          }
          if (!latLon) return null;
          return { lat: latLon.lat, lon: latLon.lon > 180 ? latLon.lon - 360 : latLon.lon };
        },
        // ── The viewer's own card, for a shared layer's click ────────────
        // A layer that names places (the IAU outlines) answers a click with
        // THIS card, not the GIS stack card beside it -- one card per click.
        // Where the viewer already labels the place, its own entry opens, so
        // the hand-written description and the label's selection come with it.
        //
        // Generated by services/port-viewer-seam.py -- edit the generator.
        openSceneFeature: (item) => {
          if (!item) return false;
          let own = null;
          if (item.name) scene.traverse((o) => { if (!own && o.userData?.feature?.name === item.name) own = o.userData.feature; });
          openFeature(own || item, false);
          return true;
        },
        // (end of the shared picker seam)
"""
PICK_MARK = "Screen to ground, for the shared pickers"


def apply_pick(check: bool) -> int:
    """surfaceLatLonAt on all nine, inserted just before `bodyId`."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        anchor = f'        bodyId: "{world}",\n'
        if anchor not in src:
            print(f"  {world:<9} ANCHOR MISSING (pick)")
            stale += 1
            continue
        if PICK_MARK in src:
            src = re.sub(r"[ ]*// ── Screen to ground.*?// \(end of the shared picker seam\)\n", "", src, count=1, flags=re.S)
        want = src.replace(anchor, PICK_BLOCK + anchor, 1)
        if check:
            if path.read_text(encoding="utf-8") != want:
                print(f"  {world:<9} STALE (pick)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (pick)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} pick seam written")
    return stale




if __name__ == "__main__":
    check = "--check" in sys.argv
    bad = apply(check) + apply_cards(check) + apply_cutaway(check) + apply_spin(check) + apply_pick(check)
    if check:
        print("uniform" if not bad else f"{bad} viewer(s) stale")
    sys.exit(1 if bad else 0)
