#!/usr/bin/env python3
"""Carry the Earth viewer's drawing gestures to the rocky planet viewers.

The press-drag box, the eight visible handles, the live size chip, the
hover cursors and the Escape cancel were written once, in earth-viewer.js.
Every planet viewer is a self-contained COPY of the viewer — there is no
shared module they could import, and `stamp.py` deliberately does not sweep
`planet_explorer/**/*.js` (those files carry epoch-second stamps from
another tooling convention, and an 8-digit rewrite mangles them). So the
choice is five hand-maintained copies or one generator, and this file is
the generator: the copies are marked, so re-running replaces them.

**Edit earth-viewer.js and re-run this. Never edit a generated block.**
That is the lesson the polygon-area formula cost — the same arithmetic
written out in ten places, corrected in one.

Three things are per-body and are rewritten here:

  * the scene group that carries the tilt and spin (`marsGroup` on Earth,
    Mars and the Moon; each of the other worlds has its own),
  * the kilometres in a degree — 111.32 is Earth's and nobody else's, so
    it comes off each viewer's own mean-radius constant,
  * `lonDelta`, which already means something else in these files.

Run:  python3 GeoID_GIS/services/port-draw-tools.py [--check]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EARTH = ROOT / "GeoID_GIS" / "viewer" / "earth-viewer.js"

OPEN_MARK = "// >>> GEOID-DRAW-TOOLS — generated by services/port-draw-tools.py"
CLOSE_MARK = "// <<< GEOID-DRAW-TOOLS"

# The rocky worlds. The gas giants follow, with a prelude — see GAS_BODIES.
BODIES = [
    # folder,   viewer file,          scene group,     mean-radius constant
    ("mars",    "mars-viewer.js",     "marsGroup",     "MARS_MEAN_RADIUS_KM"),
    ("moon",    "moon-viewer.js",     "marsGroup",     "MOON_MEAN_RADIUS_KM"),
    ("mercury", "mercury-viewer.js",  "mercuryGroup",  "MERCURY_MEAN_RADIUS_KM"),
    ("venus",   "venus-viewer.js",    "venusGroup",    "VENUS_MEAN_RADIUS_KM"),
    ("pluto",   "pluto-viewer.js",    "plutoGroup",    "PLUTO_MEAN_RADIUS_KM"),
]

# Where the block goes: straight after the measurement raycast it is built
# on, exactly where it sits in the Earth viewer.
ANCHOR = (
    "        return { ...hit, localPoint, lat: latLon.lat, "
    "lon: latLon.lon, context };\n      }\n"
)

BLOCK_START = "      /* ── Study-area rectangle editing"
BLOCK_END = '      window.addEventListener("pointerup", drawPointerUp, true);\n'

SEAM_OLD = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          return true;
        },
"""

SEAM_NEW = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          // Announced like an edit: gis/pipeline-sync.js listens here, so
          // every creator — a preset, the Draw HUD, a restored area — keeps
          // the open project's study area current.
          document.dispatchEvent(new Event("geoid-study-area-edited"));
          return true;
        },
        // The drawn overlay, taken down — used once a shape has been
        // CAPTURED as a real layer, so the floating outline does not double
        // the relief-hugging one beneath it.
        clearStudyArea() {
          resetActiveMeasurement();
        },
"""



# ── Measure furniture the planets never received ─────────────────────────────
#
# Three changes made on Earth that live OUTSIDE the block above, so the porter
# never carried them and five viewers kept the old behaviour. Reported as "the
# study area pop up window is still occurring" and "polygon points still
# showing a,b,c annotations", and both were exactly that.
#
# Each is (old, new, why). They are applied verbatim per viewer and are
# idempotent: a rewrite whose `new` is already present is skipped, so a re-run
# is a no-op and --check can tell stale from ported.
REWRITES = [
    (
        # 1. No corner card for an AREA. A number describing a polygon belongs
        #    ON the polygon; with two shapes drawn a corner card cannot say
        #    which one it is about, and everything else it held is in the Study
        #    Area panel, which carries strictly more.
        "          showMeasurementResultCard(`Study Area: ${areaKm2.toFixed(0)} km\u00b2`,"
        " measureMetric.innerHTML, toolRailAreaButton);\n",
        "          /**\n"
        "           * No corner card for an area \u2014 the label at its centroid says it.\n"
        "           *\n"
        "           * A number describing a polygon belongs on the polygon, not pinned\n"
        "           * to the edge of the window, and with two shapes drawn a corner\n"
        "           * card cannot say which one it is about. The terrain figures this\n"
        "           * card also held \u2014 elevation range, mean slope, geology \u2014 are in\n"
        "           * the Study Area panel, which carries strictly more of them.\n"
        "           * Distance and Route keep their cards: a line has no inside to\n"
        "           * write in.\n"
        "           */\n"
        "          hideMeasurementResultCard();\n",
        "study-area corner card",
    ),
    (
        # 2. Point letters are PROFILE furniture. On a drawn polygon they were
        #    noise over the shape's own annotation; on distance and route the
        #    segment readouts already say which end is which.
        "        // Point label (\"A\", \"B\", \"C\"\u2026)\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "        /**\n"
        "         * Point letters (\"A\", \"B\", \"C\"\u2026) are PROFILE furniture only. A\n"
        "         * profile is read against its chart, whose axis runs A\u2192B, so the\n"
        "         * letters are the join between picture and plot. On a drawn polygon\n"
        "         * they were noise over the shape's own annotation, and on distance\n"
        "         * and route the segment readouts already say which end is which.\n"
        "         */\n"
        "        if (measureMode !== \"profile\") {\n"
        "          measureVisuals.push({\n"
        "            contextKind: context.kind,\n"
        "            marker,\n"
        "            labelSprite: null,\n"
        "            markerAnchor: surfaceAnchor.clone(),\n"
        "            surfaceNormal: surfaceNormal.clone(),\n"
        "            markerEmbedFactor,\n"
        "            labelDirection: surfaceNormal.clone(),\n"
        "            baseMarkerRadius,\n"
        "            baseSpriteScale: 0,\n"
        "            baseLabelOffset: 0,\n"
        "            maxMarkerWorldRadius: baseMarkerRadius * 40,\n"
        "            targetMarkerPx: isMoon ? 11 : inMoonViewer ? 10 : (isCtxMosaicBasemap ? 6 : 8),\n"
        "            targetLabelPx: 0,\n"
        "          });\n"
        "          return;\n"
        "        }\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "profile-only point letters",
    ),
    (
        # 3. A letterless point still scales its DOT. The old guard bailed on
        #    the whole visual when there was no sprite, so every marker drawn
        #    by rewrite 2 would have frozen at its build size.
        "        for (const visual of measureVisuals) {\n"
        "          if (!visual.marker || !visual.labelSprite) {\n"
        "            continue;\n"
        "          }\n",
        "        for (const visual of measureVisuals) {\n"
        "          // A letterless point (every mode but profile) still scales its dot,\n"
        "          // so the bail-out on a missing sprite comes AFTER the marker work.\n"
        "          if (!visual.marker) {\n"
        "            continue;\n"
        "          }\n",
        "letterless dots still scale",
    ),
    (
        "          visual.labelSprite.scale.set(sScale, sScale, 1);\n",
        "          if (!visual.labelSprite) {\n"
        "            continue;\n"
        "          }\n"
        "          visual.labelSprite.scale.set(sScale, sScale, 1);\n",
        "sprite work guarded on its own",
    ),
]


REWRITES.append((
    # 5. The measure group must outrank the data band.
    #    reversePainterSortStable compares groupOrder FIRST, taken from the
    #    nearest isGroup ancestor, so a measure group at the default ZERO puts
    #    the shape being drawn under every imported layer group (51 and up)
    #    whatever its own renderOrder says. Reported as the drawn polygon and
    #    its handles hidden behind the geology; the event markers' fault, again.
    #    The replacement is lifted from Earth's own copy so the two cannot drift.
    "      const measureGroup = new THREE.Group();\n",
    "      const measureGroup = new THREE.Group();\n      /**\n       * A GROUP sorts before its children do, so this one has to outrank the\n       * data band.\n       *\n       * `reversePainterSortStable` compares groupOrder FIRST, and projectObject\n       * takes groupOrder from the nearest ancestor that isGroup. The measure\n       * geometry carries renderOrder 96-203 of its own — well above the\n       * imported band — and none of it mattered while this group sat at the\n       * default ZERO: every imported layer group carries its band (51 and up),\n       * so the shape being drawn sorted underneath the map it was being drawn\n       * on. Reported as the polygon and its handles hidden behind the geology,\n       * and it is the same fault the event markers had, in the same place.\n       *\n       * 199 is the viewer's own furniture band — pins, labels and selection\n       * rings — which is exactly what a study area being drawn is.\n       */\n      measureGroup.renderOrder = 199;\n",
    "measure group in the furniture band",
))


def rewrite(text: str, folder: str) -> tuple[str, list[str]]:
    """Apply every REWRITE, reporting which ones this viewer still needed."""
    changed = []
    for old, new, why in REWRITES:
        if new in text:
            continue                      # already ported; a re-run is a no-op
        if old not in text:
            raise SystemExit(f"{folder}: cannot find the anchor for {why}")
        text = text.replace(old, new, 1)
        changed.append(why)
    return text, changed


def earth_block() -> str:
    """The drawing apparatus, lifted verbatim from the Earth viewer."""
    src = EARTH.read_text(encoding="utf-8")
    start = src.index(BLOCK_START)
    end = src.index(BLOCK_END) + len(BLOCK_END)
    return src[start:end]


def render(block: str, group: str, radius_const: str) -> str:
    """The same code, speaking this body's own frame and units."""
    out = block
    # `lonDelta` is already a local in these files; a hoisted function
    # declaration beside a const of that name is a SyntaxError, and one
    # that only bites the world whose file happens to have both.
    out = re.sub(r"\blonDelta\b", "studyLonDelta", out)
    # A kilometre is not a degree anywhere except Earth.
    out = out.replace("111.32", "DRAW_KM_PER_DEG")
    if group != "marsGroup":
        out = re.sub(r"\bmarsGroup\b", group, out)
    header = (
        f"      {OPEN_MARK}\n"
        "      // Edit earth-viewer.js and re-run that script; a hand edit here\n"
        "      // is overwritten, and worse, silently diverges until it is.\n"
        f"      const DRAW_KM_PER_DEG = (2 * Math.PI * {radius_const}) / 360;\n"
    )
    return header + out + f"      {CLOSE_MARK}\n"


def apply(text: str, rendered: str) -> str:
    """Insert the block, or replace the one already there."""
    if OPEN_MARK in text:
        pattern = re.compile(
            r"[ \t]*" + re.escape(OPEN_MARK) + r".*?" + re.escape(CLOSE_MARK) + r"\n",
            re.DOTALL,
        )
        return pattern.sub(rendered, text, count=1)
    if text.count(ANCHOR) != 1:
        raise SystemExit(f"anchor not found exactly once ({text.count(ANCHOR)})")
    return text.replace(ANCHOR, ANCHOR + "\n" + rendered, 1)



# ── The gas giants ────────────────────────────────────────────────────────────
#
# They were left out on the grounds that they have "no surface to draw on".
# That was true of `activateStudyArea` and false of the bodies: each already
# measures an AREA natively — click out a polygon on the cloud tops, or on any
# moon in the moon viewer — through the same measurePoints the rocky worlds use.
# What they lacked was the four names the draw bar and the capture call, so the
# bar stood its shapes down and Done had nothing to capture. Reported as the
# draw window failing to open on Saturn and Neptune.
#
# So each gets a PRELUDE — the study-area primitives in the gas giants' own
# terms (a moon point is rebuilt in the moon MESH's frame, exactly as a click
# is) — then the same Earth block every rocky world carries.
GAS_BODIES = [
    # folder,    viewer file,          display name
    ("jupiter", "jupiter-viewer.js", "Jupiter"),
    ("saturn",  "saturn-viewer.js",  "Saturn"),
    ("uranus",  "uranus-viewer.js",  "Uranus"),
    ("neptune", "neptune-viewer.js", "Neptune"),
]

GAS_ANCHOR = (
    "        return { ...hit, localPoint, moonMeshLocal, lat: latLon.lat, "
    "lon: latLon.lon, context };\n      }\n"
)

GAS_OPEN = "// >>> GEOID-GAS-STUDY-AREA — generated by services/port-draw-tools.py"
GAS_CLOSE = "// <<< GEOID-GAS-STUDY-AREA"

GAS_PRELUDE = """      __OPEN__
      // What the draw block below calls and a rocky viewer defines for itself.
      // `var`, not `let`: setMeasureMode and resetActiveMeasurement sit ABOVE
      // this and can run during boot, before a `let` here would exist.
      var measureDrawActive = false;
      // Moon measurements are placed from `moonMeshLocal` each frame (see
      // updateMeasureVisualScale), so there is no separate moon group.
      var moonMeasureGroup = null;

      function getMeasureDisplayLift(context = getActiveMeasureContext()) {
        if (context && context.kind === "moon") return context.radiusWorld * 0.02;
        return measureDisplayLiftForView();
      }

      function polygonCentroidLatLon(points) {
        if (!Array.isArray(points) || !points.length) return null;
        const normal = points.reduce((acc, point) => (
          acc.add(latLonToVector3(point.lat, point.lon, 1))
        ), new THREE.Vector3());
        if (normal.lengthSq() < 1e-9) return { lat: points[0].lat, lon: points[0].lon };
        return vectorToLatLon(normal.normalize());
      }

      /**
       * One study-area vertex, built the way a CLICK builds it.
       *
       * On a moon, latitude and longitude are the texture frame of the moon
       * mesh (intersectMeasurementSurface reads them off the mesh-local hit),
       * so the point is rebuilt in that frame by the exact inverse of
       * vectorToLatLon and carried out through the mesh — and it keeps its
       * `moonMeshLocal`, which is what holds a measurement on a turning moon.
       */
      function studyAreaVertex(vertex, context) {
        const lat = Number(vertex.lat);
        const lon = Number(vertex.lon);
        const base = {
          lat, lon,
          bodyKind: context.kind,
          bodyName: context.bodyName,
          radiusKm: context.radiusKm,
          radiusWorld: context.radiusWorld,
          context: cloneMeasureContext(context),
        };
        if (context.kind === "moon" && context.mesh) {
          const mesh = context.mesh;
          if (!mesh.geometry.boundingSphere) mesh.geometry.computeBoundingSphere();
          const r = mesh.geometry.boundingSphere.radius;
          const phi = THREE.MathUtils.degToRad(lat);
          const lam = THREE.MathUtils.degToRad(lon);
          const moonMeshLocal = new THREE.Vector3(
            -r * Math.cos(phi) * Math.cos(lam), r * Math.sin(phi), r * Math.cos(phi) * Math.sin(lam));
          mesh.updateMatrixWorld(true);
          const world = mesh.localToWorld(moonMeshLocal.clone());
          const localPoint = normalizeMeasureHitLocalPoint(marsGroup.worldToLocal(world), context);
          return { ...base, point: localPoint.clone(), localPoint: localPoint.clone(), moonMeshLocal, moonMesh: mesh };
        }
        const localPoint = sampleMeasureSurfacePoint(lat, lon, 0.012, context);
        return { ...base, point: localPoint.clone(), localPoint: localPoint.clone(), moonMeshLocal: null, moonMesh: null };
      }

      // `context` is the body the shape is ON. The draw bar's gestures pass
      // nothing and draw on whatever body is being viewed; the seam passes
      // the planet, because a GIS extent is in the planet's coordinates.
      /**
       * Where a moon latitude/longitude is in WORLD space: rebuilt in the moon
       * mesh's own frame (the exact inverse of vectorToLatLon, as the vertex
       * builder above does) and carried out through the mesh, so it turns with
       * the moon. `lift` raises it off the surface, in world units.
       */
      function moonMeshWorldPoint(lat, lon, context, lift = 0) {
        // A shape's stored context is a CLONE without the mesh (it must not
        // hold a scene object); the points themselves carry it.
        const mesh = context?.mesh
          || measurePoints.find((p) => p.moonMesh && p.bodyName === context?.bodyName)?.moonMesh
          || (getActiveMeasureContext()?.bodyName === context?.bodyName ? getActiveMeasureContext()?.mesh : null);
        if (!mesh) return null;
        if (!mesh.geometry.boundingSphere) mesh.geometry.computeBoundingSphere();
        const r = mesh.geometry.boundingSphere.radius;
        const phi = THREE.MathUtils.degToRad(Number(lat));
        const lam = THREE.MathUtils.degToRad(Number(lon));
        const local = new THREE.Vector3(
          -r * Math.cos(phi) * Math.cos(lam), r * Math.sin(phi), r * Math.cos(phi) * Math.sin(lam));
        mesh.updateMatrixWorld(true);
        const world = mesh.localToWorld(local.clone());
        if (lift > 0) {
          const centre = mesh.getWorldPosition(new THREE.Vector3());
          world.add(world.clone().sub(centre).normalize().multiplyScalar(lift));
        }
        return world;
      }

      function activateStudyArea(vertices, context = getActiveMeasureContext()) {
        if (!Array.isArray(vertices) || vertices.length < 3) return;
        if (!context) return;
        measureMode = "area";
        // Clears the old points and syncs every rail and panel button to
        // "area" — the same path the rail's own Area button takes.
        resetActiveMeasurement(true);
        measureDrawActive = false;
        measurePoints = vertices.map((vertex) => studyAreaVertex(vertex, context));
        updateMeasureVisualization();
      }

      // The GIS side — extraction, saving to the Workspace, fetch extents —
      // speaks the PLANET's coordinates. A shape on a moon is not one of its
      // geometries: handed over, its latitudes would be laid on the planet.
      function getExtractionGeometry(sourceType) {
        if (measureMode === "area" && measurePoints.length >= 3
            && measurePoints[0].bodyKind !== "moon") {
          return {
            name: "study-area",
            vertices: measurePoints.map((point) => ({ lat: point.lat, lon: point.lon })),
            center: measurePoints[0],
            body: measurePoints[0].bodyName,
          };
        }
        return null;
      }
      __CLOSE__
"""

GAS_SEAM_ANCHOR = "        earthSceneGroup: marsGroup,\n"
GAS_SEAM_MARK = "Study areas, published for the draw bar and the capture"
GAS_SEAM = """        // ── Study areas, published for the draw bar and the capture ──────
        // Generated by services/port-draw-tools.py — do not hand-edit.
        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices, planetMeasureContext());
          document.dispatchEvent(new Event("geoid-study-area-edited"));
          return true;
        },
        clearStudyArea() {
          resetActiveMeasurement();
        },
        // The body a live shape is on when it is NOT the planet, so saving it
        // can say why it will not go into the planet's Workspace.
        studyAreaOtherBody: () => (measureMode === "area" && measurePoints.length >= 3
          && measurePoints[0].bodyKind === "moon") ? measurePoints[0].bodyName : null,
        getExtractionGeometry: (sourceType) => getExtractionGeometry(sourceType),
        // ── end study areas ──
"""

GAS_REWRITES = [
    (
        # The draw block reads `measureDrawActive` as "the area tool is armed
        # for a NEW shape", which the rocky setMeasureMode sets and this one
        # did not.
        '        measureMode = measureMode === nextMode ? "" : nextMode;\n'
        "        resetActiveMeasurement(true);\n",
        '        measureMode = measureMode === nextMode ? "" : nextMode;\n'
        "        measureDrawActive = Boolean(measureMode);\n"
        "        resetActiveMeasurement(true);\n",
        "draw-armed flag on mode change",
    ),
    (
        "        if (!preserveMode) {\n"
        '          measureMode = "";\n'
        "        }\n"
        "        measurePoints = [];\n",
        "        if (!preserveMode) {\n"
        '          measureMode = "";\n'
        "          measureDrawActive = false;\n"
        "        }\n"
        "        measurePoints = [];\n",
        "draw-armed flag on reset",
    ),
    (
        # A tap while the bar is still waiting for a shape places nothing. The
        # rocky viewers add vertices on `click`, which the block swallows; these
        # add them on pointerup, so the same rule is written where they do it.
        "        if (measureMode) {\n"
        "          const surfaceHit = intersectMeasurementSurface(event.clientX, event.clientY);\n",
        "        if (measureMode && !(measureMode === \"area\" && measureDrawActive && !chosenDrawShape())) {\n"
        "          const surfaceHit = intersectMeasurementSurface(event.clientX, event.clientY);\n",
        "no vertex while the bar awaits a shape",
    ),
]


GAS_FURNITURE = [
    (
        # Point letters are PROFILE furniture only — the rocky rule, in this
        # lineage's own variables (moon markers keep their mesh frame).
        "        // Point label (\"A\", \"B\", \"C\"…)\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "        /**\n"
        "         * Point letters (\"A\", \"B\", \"C\"…) are PROFILE furniture only, as on\n"
        "         * every rocky world: a profile is read against its chart, whose axis\n"
        "         * runs A→B. On a drawn polygon they were noise over its annotation.\n"
        "         */\n"
        "        if (measureMode !== \"profile\") {\n"
        "          measureVisuals.push({\n"
        "            marker,\n"
        "            labelSprite: null,\n"
        "            markerAnchor: markerPos.clone(),\n"
        "            surfaceNormal: surfaceNormal.clone(),\n"
        "            baseLabelOffset: 0,\n"
        "            baseMarkerRadius,\n"
        "            targetMarkerPx: isMoon ? 11 : 8,\n"
        "            targetLabelPx: 0,\n"
        "            maxMarkerWorldRadius: isMoon ? context.radiusWorld * 0.06 : 0.04,\n"
        "            moonMesh: (isMoon && point.moonMesh) ? point.moonMesh : null,\n"
        "            moonLocalLiftedPt,\n"
        "            moonLocalNormal,\n"
        "          });\n"
        "          return;\n"
        "        }\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "profile-only point letters",
    ),
    (
        "          if (!visual.marker || !visual.labelSprite) continue;\n",
        "          // A letterless point still scales its dot; the label work is\n"
        "          // guarded on its own below.\n"
        "          if (!visual.marker) continue;\n",
        "letterless dots still scale",
    ),
    (
        "          visual.labelSprite.scale.set(spriteScale, spriteScale, 1);\n",
        "          if (!visual.labelSprite) continue;\n"
        "          visual.labelSprite.scale.set(spriteScale, spriteScale, 1);\n",
        "sprite work guarded on its own",
    ),
    (
        "      const measureGroup = new THREE.Group();\n",
        "      const measureGroup = new THREE.Group();\n"
        "      // The furniture band, as on every rocky world: a GROUP sorts before\n"
        "      // its children, so at the default zero the shape being drawn sorted\n"
        "      // under every imported layer group (51 and up).\n"
        "      measureGroup.renderOrder = 199;\n",
        "measure group in the furniture band",
    ),
]


def gas_apply(text: str, block: str, display: str) -> tuple[str, list[str]]:
    changed = []
    prelude = (GAS_PRELUDE.replace("__OPEN__", GAS_OPEN).replace("__CLOSE__", GAS_CLOSE))
    rendered = render(block, "marsGroup", "MARS_MEAN_RADIUS_KM")
    combined = prelude + rendered
    if GAS_OPEN in text:
        pattern = re.compile(r"[ \t]*" + re.escape(GAS_OPEN) + r".*?" + re.escape(CLOSE_MARK) + r"\n", re.DOTALL)
        text = pattern.sub(lambda _m: combined, text, count=1)
    else:
        if text.count(GAS_ANCHOR) != 1:
            raise SystemExit(f"{display}: gas anchor found {text.count(GAS_ANCHOR)} times")
        text = text.replace(GAS_ANCHOR, GAS_ANCHOR + "\n" + combined, 1)
    if GAS_SEAM_MARK in text:
        text = re.sub(r"[ ]*// ── Study areas, published.*?// ── end study areas ──\n", "", text, flags=re.S)
    if text.count(GAS_SEAM_ANCHOR) != 1:
        raise SystemExit(f"{display}: seam anchor found {text.count(GAS_SEAM_ANCHOR)} times")
    text = text.replace(GAS_SEAM_ANCHOR, GAS_SEAM_ANCHOR + GAS_SEAM, 1)
    for old, new, why in GAS_REWRITES:
        if new in text:
            continue
        if text.count(old) != 1:
            raise SystemExit(f"{display}: cannot find the anchor for {why}")
        text = text.replace(old, new, 1)
        changed.append(why)
    # The rocky measure-furniture rewrites are NOT applied here: their
    # replacements name locals (surfaceAnchor, markerEmbedFactor, inMoonViewer)
    # this lineage does not have, and would throw on the first vertex. The same
    # three decisions are written in this lineage's own terms instead.
    for old, new, why in GAS_FURNITURE:
        if new in text:
            continue
        if text.count(old) != 1:
            raise SystemExit(f"{display}: cannot find the anchor for {why}")
        text = text.replace(old, new, 1)
        changed.append(why)
    return text, changed


def main() -> int:
    check = "--check" in sys.argv
    block = earth_block()
    stale = []
    for folder, viewer, group, radius_const in BODIES:
        path = ROOT / "planet_explorer" / folder / "viewer" / viewer
        text = path.read_text(encoding="utf-8")
        if radius_const not in text:
            raise SystemExit(f"{folder}: {radius_const} not found")
        updated = apply(text, render(block, group, radius_const))
        # The seam the HUD's Done and Cancel need, and the announcement the
        # pipeline sync listens for.
        if SEAM_OLD in updated:
            updated = updated.replace(SEAM_OLD, SEAM_NEW, 1)
        elif "clearStudyArea()" not in updated:
            raise SystemExit(f"{folder}: setStudyAreaPolygon seam not recognised")
        updated, rewrote = rewrite(updated, folder)
        if updated == text:
            print(f"  {folder:8s} unchanged")
            continue
        if rewrote:
            print(f"  {folder:8s} + {', '.join(rewrote)}")
        stale.append(folder)
        if not check:
            path.write_text(updated, encoding="utf-8")
        print(f"  {folder:8s} {'STALE' if check else 'ported'}")
    for folder, viewer, display in GAS_BODIES:
        path = ROOT / "planet_explorer" / folder / "viewer" / viewer
        text = path.read_text(encoding="utf-8")
        updated, rewrote = gas_apply(text, block, display)
        if updated == text:
            print(f"  {folder:8s} unchanged")
            continue
        if rewrote:
            print(f"  {folder:8s} + {', '.join(rewrote)}")
        stale.append(folder)
        if not check:
            path.write_text(updated, encoding="utf-8")
        print(f"  {folder:8s} {'STALE' if check else 'ported'}")
    if check and stale:
        print(f"drawing tools out of date on: {', '.join(stale)}")
        return 1
    print("uniform" if not stale else f"ported {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
