#!/usr/bin/env python3
"""Carry the Earth viewer's drawing gestures to the rocky planet viewers.

The press-drag box, the eight visible handles, the live size chip, the
hover cursors and the Escape cancel were written once, in earth-viewer.js.
Every planet viewer is a self-contained COPY of the viewer — there is no
shared module they could import, and `stamp.py` deliberately does not sweep
`planet_explorer/**/*.js` (those files carry epoch-second stamps from
another tooling convention, and an 8-digit rewrite mangles them). So the
choice is five hand-maintained copies or one generator, and this file is
the generator: the copies are marked, so re-running replaces them.

**Edit earth-viewer.js and re-run this. Never edit a generated block.**
That is the lesson the polygon-area formula cost — the same arithmetic
written out in ten places, corrected in one.

Three things are per-body and are rewritten here:

  * the scene group that carries the tilt and spin (`marsGroup` on Earth,
    Mars and the Moon; each of the other worlds has its own),
  * the kilometres in a degree — 111.32 is Earth's and nobody else's, so
    it comes off each viewer's own mean-radius constant,
  * `lonDelta`, which already means something else in these files.

Run:  python3 GeoID_GIS/services/port-draw-tools.py [--check]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EARTH = ROOT / "GeoID_GIS" / "viewer" / "earth-viewer.js"

OPEN_MARK = "// >>> GEOID-DRAW-TOOLS — generated by services/port-draw-tools.py"
CLOSE_MARK = "// <<< GEOID-DRAW-TOOLS"

# The gas giants are absent on purpose: they have no activateStudyArea and
# no surface to draw on. That is a fact about the bodies, not a gap.
BODIES = [
    # folder,   viewer file,          scene group,     mean-radius constant
    ("mars",    "mars-viewer.js",     "marsGroup",     "MARS_MEAN_RADIUS_KM"),
    ("moon",    "moon-viewer.js",     "marsGroup",     "MOON_MEAN_RADIUS_KM"),
    ("mercury", "mercury-viewer.js",  "mercuryGroup",  "MERCURY_MEAN_RADIUS_KM"),
    ("venus",   "venus-viewer.js",    "venusGroup",    "VENUS_MEAN_RADIUS_KM"),
    ("pluto",   "pluto-viewer.js",    "plutoGroup",    "PLUTO_MEAN_RADIUS_KM"),
]

# Where the block goes: straight after the measurement raycast it is built
# on, exactly where it sits in the Earth viewer.
ANCHOR = (
    "        return { ...hit, localPoint, lat: latLon.lat, "
    "lon: latLon.lon, context };\n      }\n"
)

BLOCK_START = "      /* ── Study-area rectangle editing"
BLOCK_END = '      window.addEventListener("pointerup", drawPointerUp, true);\n'

SEAM_OLD = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          return true;
        },
"""

SEAM_NEW = """        setStudyAreaPolygon(vertices) {
          if (!Array.isArray(vertices) || vertices.length < 3) return false;
          activateStudyArea(vertices);
          // Announced like an edit: gis/pipeline-sync.js listens here, so
          // every creator — a preset, the Draw HUD, a restored area — keeps
          // the open project's study area current.
          document.dispatchEvent(new Event("geoid-study-area-edited"));
          return true;
        },
        // The drawn overlay, taken down — used once a shape has been
        // CAPTURED as a real layer, so the floating outline does not double
        // the relief-hugging one beneath it.
        clearStudyArea() {
          resetActiveMeasurement();
        },
"""



# ── Measure furniture the planets never received ─────────────────────────────
#
# Three changes made on Earth that live OUTSIDE the block above, so the porter
# never carried them and five viewers kept the old behaviour. Reported as "the
# study area pop up window is still occurring" and "polygon points still
# showing a,b,c annotations", and both were exactly that.
#
# Each is (old, new, why). They are applied verbatim per viewer and are
# idempotent: a rewrite whose `new` is already present is skipped, so a re-run
# is a no-op and --check can tell stale from ported.
REWRITES = [
    (
        # 1. No corner card for an AREA. A number describing a polygon belongs
        #    ON the polygon; with two shapes drawn a corner card cannot say
        #    which one it is about, and everything else it held is in the Study
        #    Area panel, which carries strictly more.
        "          showMeasurementResultCard(`Study Area: ${areaKm2.toFixed(0)} km\u00b2`,"
        " measureMetric.innerHTML, toolRailAreaButton);\n",
        "          /**\n"
        "           * No corner card for an area \u2014 the label at its centroid says it.\n"
        "           *\n"
        "           * A number describing a polygon belongs on the polygon, not pinned\n"
        "           * to the edge of the window, and with two shapes drawn a corner\n"
        "           * card cannot say which one it is about. The terrain figures this\n"
        "           * card also held \u2014 elevation range, mean slope, geology \u2014 are in\n"
        "           * the Study Area panel, which carries strictly more of them.\n"
        "           * Distance and Route keep their cards: a line has no inside to\n"
        "           * write in.\n"
        "           */\n"
        "          hideMeasurementResultCard();\n",
        "study-area corner card",
    ),
    (
        # 2. Point letters are PROFILE furniture. On a drawn polygon they were
        #    noise over the shape's own annotation; on distance and route the
        #    segment readouts already say which end is which.
        "        // Point label (\"A\", \"B\", \"C\"\u2026)\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "        /**\n"
        "         * Point letters (\"A\", \"B\", \"C\"\u2026) are PROFILE furniture only. A\n"
        "         * profile is read against its chart, whose axis runs A\u2192B, so the\n"
        "         * letters are the join between picture and plot. On a drawn polygon\n"
        "         * they were noise over the shape's own annotation, and on distance\n"
        "         * and route the segment readouts already say which end is which.\n"
        "         */\n"
        "        if (measureMode !== \"profile\") {\n"
        "          measureVisuals.push({\n"
        "            contextKind: context.kind,\n"
        "            marker,\n"
        "            labelSprite: null,\n"
        "            markerAnchor: surfaceAnchor.clone(),\n"
        "            surfaceNormal: surfaceNormal.clone(),\n"
        "            markerEmbedFactor,\n"
        "            labelDirection: surfaceNormal.clone(),\n"
        "            baseMarkerRadius,\n"
        "            baseSpriteScale: 0,\n"
        "            baseLabelOffset: 0,\n"
        "            maxMarkerWorldRadius: baseMarkerRadius * 40,\n"
        "            targetMarkerPx: isMoon ? 11 : inMoonViewer ? 10 : (isCtxMosaicBasemap ? 6 : 8),\n"
        "            targetLabelPx: 0,\n"
        "          });\n"
        "          return;\n"
        "        }\n"
        "        const letter = String.fromCharCode(65 + (index || 0));\n",
        "profile-only point letters",
    ),
    (
        # 3. A letterless point still scales its DOT. The old guard bailed on
        #    the whole visual when there was no sprite, so every marker drawn
        #    by rewrite 2 would have frozen at its build size.
        "        for (const visual of measureVisuals) {\n"
        "          if (!visual.marker || !visual.labelSprite) {\n"
        "            continue;\n"
        "          }\n",
        "        for (const visual of measureVisuals) {\n"
        "          // A letterless point (every mode but profile) still scales its dot,\n"
        "          // so the bail-out on a missing sprite comes AFTER the marker work.\n"
        "          if (!visual.marker) {\n"
        "            continue;\n"
        "          }\n",
        "letterless dots still scale",
    ),
    (
        "          visual.labelSprite.scale.set(sScale, sScale, 1);\n",
        "          if (!visual.labelSprite) {\n"
        "            continue;\n"
        "          }\n"
        "          visual.labelSprite.scale.set(sScale, sScale, 1);\n",
        "sprite work guarded on its own",
    ),
]


def rewrite(text: str, folder: str) -> tuple[str, list[str]]:
    """Apply every REWRITE, reporting which ones this viewer still needed."""
    changed = []
    for old, new, why in REWRITES:
        if new in text:
            continue                      # already ported; a re-run is a no-op
        if old not in text:
            raise SystemExit(f"{folder}: cannot find the anchor for {why}")
        text = text.replace(old, new, 1)
        changed.append(why)
    return text, changed


def earth_block() -> str:
    """The drawing apparatus, lifted verbatim from the Earth viewer."""
    src = EARTH.read_text(encoding="utf-8")
    start = src.index(BLOCK_START)
    end = src.index(BLOCK_END) + len(BLOCK_END)
    return src[start:end]


def render(block: str, group: str, radius_const: str) -> str:
    """The same code, speaking this body's own frame and units."""
    out = block
    # `lonDelta` is already a local in these files; a hoisted function
    # declaration beside a const of that name is a SyntaxError, and one
    # that only bites the world whose file happens to have both.
    out = re.sub(r"\blonDelta\b", "studyLonDelta", out)
    # A kilometre is not a degree anywhere except Earth.
    out = out.replace("111.32", "DRAW_KM_PER_DEG")
    if group != "marsGroup":
        out = re.sub(r"\bmarsGroup\b", group, out)
    header = (
        f"      {OPEN_MARK}\n"
        "      // Edit earth-viewer.js and re-run that script; a hand edit here\n"
        "      // is overwritten, and worse, silently diverges until it is.\n"
        f"      const DRAW_KM_PER_DEG = (2 * Math.PI * {radius_const}) / 360;\n"
    )
    return header + out + f"      {CLOSE_MARK}\n"


def apply(text: str, rendered: str) -> str:
    """Insert the block, or replace the one already there."""
    if OPEN_MARK in text:
        pattern = re.compile(
            r"[ \t]*" + re.escape(OPEN_MARK) + r".*?" + re.escape(CLOSE_MARK) + r"\n",
            re.DOTALL,
        )
        return pattern.sub(rendered, text, count=1)
    if text.count(ANCHOR) != 1:
        raise SystemExit(f"anchor not found exactly once ({text.count(ANCHOR)})")
    return text.replace(ANCHOR, ANCHOR + "\n" + rendered, 1)


def main() -> int:
    check = "--check" in sys.argv
    block = earth_block()
    stale = []
    for folder, viewer, group, radius_const in BODIES:
        path = ROOT / "planet_explorer" / folder / "viewer" / viewer
        text = path.read_text(encoding="utf-8")
        if radius_const not in text:
            raise SystemExit(f"{folder}: {radius_const} not found")
        updated = apply(text, render(block, group, radius_const))
        # The seam the HUD's Done and Cancel need, and the announcement the
        # pipeline sync listens for.
        if SEAM_OLD in updated:
            updated = updated.replace(SEAM_OLD, SEAM_NEW, 1)
        elif "clearStudyArea()" not in updated:
            raise SystemExit(f"{folder}: setStudyAreaPolygon seam not recognised")
        updated, rewrote = rewrite(updated, folder)
        if updated == text:
            print(f"  {folder:8s} unchanged")
            continue
        if rewrote:
            print(f"  {folder:8s} + {', '.join(rewrote)}")
        stale.append(folder)
        if not check:
            path.write_text(updated, encoding="utf-8")
        print(f"  {folder:8s} {'STALE' if check else 'ported'}")
    if check and stale:
        print(f"drawing tools out of date on: {', '.join(stale)}")
        return 1
    print("uniform" if not stale else f"ported {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
