#!/usr/bin/env python3
"""
Publish each rocky viewer's own terrain primitives on the GIS seam.

The GIS tools ARE one shared module set — 51 modules under `viewer/gis/`, the
same 47-tool registry and the same draw bar on every world. What was NOT shared
is the SEAM those modules call into: `window.GeoIDViewer`. Measured live on
Mars, three names the shared modules use were simply absent:

    surfacePoint          vector-render, the drapes, anything that hugs terrain
    getEffectiveRelief    vector-render, geotiff-adapter
    elevationNormalized   vector-render

Every one of those is already COMPUTED inside each planet viewer — as
`measureSurfaceRadius`, `getEffectiveTerrainRelief` and
`sampleElevationNormalized`. They were just never published, so a shared module
loaded on a planet asked for them and got `undefined`.

So this does not re-derive the terrain rule in a shared module, which is the
"second implementation drifts" trap this tree has paid for repeatedly (the
polygon-area formula in ten files, the imitated label engine, the fan apex).
It exposes what each viewer already has, in that viewer's own frame.

`surfacePoint` passes an explicit `{ kind: "planet" }` context rather than
letting `measureSurfaceRadius` default to `getActiveMeasureContext()`: the
default would answer in a MOON's frame whenever a moon happens to be the active
measure target, and a caller asking for a point on the planet must get one.

The four gas giants are deliberately untouched: they have no elevation map and
no `getEffectiveTerrainRelief`, so there is nothing to publish and nothing that
hugs their terrain.

Run:  python3 GeoID_GIS/services/port-viewer-seam.py [--check]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORLDS = ["mars", "mercury", "moon", "venus", "pluto"]

# The card seam goes to ALL NINE: a gas giant has no terrain to hug, but it has
# a scene card, and leaving GIS has to dismiss it there too.
CARD_WORLDS = WORLDS + ["jupiter", "saturn", "uranus", "neptune"]

# The seam literal already lists this; the new entries go directly after it.
ANCHOR = "        sphericalPolygonAreaKm2,\n"

BLOCK = """        // ── Terrain seam, published for the shared GIS modules ──────────
        // These three are what vector-render and the raster adapters ask a
        // viewer for so their geometry can hug the ground. Each is this
        // viewer's OWN computation, exposed rather than re-derived: a second
        // copy of the radius rule is exactly how the polygon-area formula came
        // to be wrong in ten files.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        surfacePoint: (lat, lon, lift = 0) => latLonToVector3(
          lat, lon, measureSurfaceRadius(lat, lon, lift, { kind: "planet" })),
        getEffectiveRelief: () => getEffectiveTerrainRelief(),
        elevationNormalized: (lat, lon) => (elevationSampler
          ? sampleElevationNormalized(elevationSampler, lat, lon) : 0),
"""

MARK = "Terrain seam, published for the shared GIS modules"

CARD_BLOCK = """        // ── Floating cards, so a mode change can dismiss them ───────────
        // A scene card is a fixed element on `body`, so nothing that hides the
        // sidebar touches it: leaving GIS left one standing over the Model
        // studio and the Research Hub. It closes through each card's OWN
        // closer, because `closeScenePopup` also clears the temporary
        // selection label and the selection halo — hiding the element alone
        // strands a pulsing marker on a globe nobody can see.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        closeCards: () => {
          if (typeof closeScenePopup === "function") closeScenePopup();
          if (typeof closeGeoPopup === "function") closeGeoPopup();
          if (typeof hideMeasurementResultCard === "function") hideMeasurementResultCard();
        },
"""

CARD_MARK = "Floating cards, so a mode change can dismiss them"


def target(world: str) -> Path:
    return ROOT / "planet_explorer" / world / "viewer" / f"{world}-viewer.js"


def apply_cards(check: bool) -> int:
    """The card seam, on every world including the four gas giants."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        anchor = f'        bodyId: "{world}",\n'
        if anchor not in src:
            print(f"  {world:<9} ANCHOR MISSING (cards)")
            stale += 1
            continue
        if CARD_MARK in src:
            src = re.sub(
                r"[ ]*// ── Floating cards.*?\n[ ]*\},\n", "", src, flags=re.S)
        want = src.replace(anchor, anchor + CARD_BLOCK, 1)
        if check:
            if path.read_text(encoding="utf-8") != want:
                print(f"  {world:<9} STALE (cards)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (cards)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} card seam written")
    return stale


def apply(check: bool) -> int:
    stale = 0
    for world in WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        if ANCHOR not in src:
            print(f"  {world:<9} ANCHOR MISSING — seam literal changed shape")
            stale += 1
            continue
        # Idempotent: strip a previous block before writing the current one.
        if MARK in src:
            src = re.sub(
                r"[ ]*// ── Terrain seam.*?elevationNormalized: \(lat, lon\) => \(elevationSampler\n"
                r".*?: 0\),\n",
                "", src, flags=re.S)
        want = src.replace(ANCHOR, ANCHOR + BLOCK, 1)
        if check:
            current = path.read_text(encoding="utf-8")
            if current != want:
                print(f"  {world:<9} STALE")
                stale += 1
            else:
                print(f"  {world:<9} up to date")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} seam published")
    return stale


CUT_BLOCK = """        // ── What the scene is cut by, so a layer can cut itself ─────────
        // Core View removes half the planet with one world-space clipping
        // plane, and that plane was applied to a hand-written list of this
        // viewer's OWN materials. Everything the shared GIS modules draw was
        // outside that list, so with the cutaway up a coastline, a marker
        // cloud or a dot layer went on being drawn across the removed half.
        //
        // A list cannot be the answer -- a layer's materials are built by the
        // importer, the tilers, the drapes and the repaints -- so the plane is
        // published and `gis/cutaway.js` stamps whatever is on the globe now.
        // Live rather than copied: the normal is re-aimed whenever the axial
        // tilt changes, and three.js reads clipping planes in WORLD space.
        //
        // Generated by services/port-viewer-seam.py — do not hand-edit; edit
        // the generator and re-run it.
        getCutawayPlanes: () => (coreToggle && coreToggle.checked ? [cutawayClipPlane] : []),
"""

CUT_MARK = "What the scene is cut by, so a layer can cut itself"

# The last line of CARD_BLOCK. Anchoring here rather than on `bodyId` keeps the
# two blocks in a FIXED order however often the porter is re-run: `apply_cards`
# strips and re-inserts its own block at `bodyId`, which puts it back above
# this one, and this block is re-inserted after it. Anchored both on `bodyId`
# the order would flip on every run and `--check` would never settle.
CUT_ANCHOR = ('          if (typeof hideMeasurementResultCard === "function")'
              " hideMeasurementResultCard();\n        },\n")

# The one line every viewer's core toggle builds its plane list on.
TOGGLE_ANCHOR = "        const planes = enabled ? [cutawayClipPlane] : [];\n"

TOGGLE_BLOCK = """        // Announced, because the layers are not ours to enumerate: the
        // viewer stamps its own materials inline and everything the GIS page
        // put on the globe hears this instead. A plain Event on `document`,
        // which is this tree's own viewer-side convention.
        // Generated by services/port-viewer-seam.py — do not hand-edit.
        document.dispatchEvent(new Event("geoid-gis:cutaway-changed"));
"""

TOGGLE_MARK = "Announced, because the layers are not ours to enumerate"


def apply_cutaway(check: bool) -> int:
    """The cutaway seam and its announcement, on every world -- gas giants
    included, since all ten have a core toggle and all ten take layers."""
    stale = 0
    for world in CARD_WORLDS:
        path = target(world)
        src = path.read_text(encoding="utf-8")
        want = src
        if CUT_MARK in want:
            want = re.sub(r"[ ]*// ── What the scene is cut by.*?getCutawayPlanes:.*?\n",
                          "", want, flags=re.S)
        if TOGGLE_MARK in want:
            want = re.sub(r"[ ]*// Announced, because the layers are not ours.*?"
                          r'document\.dispatchEvent\(new Event\("geoid-gis:cutaway-changed"\)\);\n',
                          "", want, flags=re.S)
        if CUT_ANCHOR not in want or TOGGLE_ANCHOR not in want:
            missing = "card block" if CUT_ANCHOR not in want else "core toggle"
            print(f"  {world:<9} ANCHOR MISSING ({missing})")
            stale += 1
            continue
        want = want.replace(CUT_ANCHOR, CUT_ANCHOR + CUT_BLOCK, 1)
        want = want.replace(TOGGLE_ANCHOR, TOGGLE_BLOCK + TOGGLE_ANCHOR, 1)
        if check:
            if path.read_text(encoding="utf-8") != want:
                print(f"  {world:<9} STALE (cutaway)")
                stale += 1
            else:
                print(f"  {world:<9} up to date (cutaway)")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"  {world:<9} cutaway seam written")
    return stale


if __name__ == "__main__":
    check = "--check" in sys.argv
    bad = apply(check) + apply_cards(check) + apply_cutaway(check)
    if check:
        print("uniform" if not bad else f"{bad} viewer(s) stale")
    sys.exit(1 if bad else 0)
