#!/usr/bin/env python3
"""Regenerate the homepage "What's new" grid from data/updates.json.

Usage:
    python3 scripts/make-updates.py

Posting an update is now a two-minute job:
  1. add an entry to data/updates.json (first entry = lead story)
  2. run this script
  3. commit both files

The script only touches index.html between the UPDATES:START/END markers,
so the rest of the page — and every other page — is never at risk. It is
a build step, not runtime JS: the grid stays static HTML, so search
engines and no-JS visitors see the same content as everyone else.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FEED = ROOT / "data" / "updates.json"
PAGE = ROOT / "index.html"

START = "<!-- UPDATES:START (generated by scripts/make-updates.py — edit data/updates.json instead) -->"
END = "<!-- UPDATES:END -->"


def esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def tile(u: dict, lead: bool) -> str:
    classes = ["story"]
    if lead:
        classes.append("story--lead")
    if u["status"] == "live":
        classes.append("story--live")
    elif u["status"] == "dev":
        classes.append("story--dev")
    delay = "0ms" if lead else "110ms"
    return f"""        <a class="{' '.join(classes)} rise" style="--d:{delay}" href="{esc(u['href'])}">
          <div class="story-media"><img src="{esc(u['image'])}" alt="{esc(u['alt'])}" loading="lazy" decoding="async"></div>
          <span class="story-kicker">{esc(u['kicker'])}</span>
          <h3 class="story-title">{esc(u['title'])}</h3>
          <p class="story-desc">{esc(u['desc'])}</p>
        </a>"""


def main() -> int:
    feed = json.loads(FEED.read_text())
    updates = feed["updates"]
    if not updates:
        print("feed is empty — nothing to do", file=sys.stderr)
        return 1

    tiles = "\n\n".join(tile(u, i == 0) for i, u in enumerate(updates))
    block = f"{START}\n{tiles}\n      {END}"

    page = PAGE.read_text()
    if START in page:
        page = re.sub(re.escape(START) + r".*?" + re.escape(END), block, page, flags=re.S)
    else:
        # First run: replace the static grid contents wholesale.
        m = re.search(r'(<div class="news">\n)(.*?)(\n      </div>)', page, re.S)
        if not m:
            print("could not find the news grid in index.html", file=sys.stderr)
            return 1
        page = page[:m.start(2)] + block + page[m.end(2):]

    PAGE.write_text(page)
    print(f"wrote {len(updates)} tiles into index.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
